apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "2+OMn+f46CnuObU+iASUKM4qeBzccnS1izBvW0ln+8YGNso0v1H7ZPJg4UxFaVue\nx74woYZyJ+ugvPch2q7DDslkIDoho5lXD5z7Bo7bw2rRHbCrTp69vErGlZ0gtIjZ\nNZ5r924GZky03wxgrE+A8XHCnpVUfMFIBWfdqEBwUuA="
